### ISSUE TITLE
US# | Actualizar datos como médico.

### ISSUE THREAD

**Issue by FrancoSer** [FrancoSer/ISPC_2do_semestre_2022#17]
US#6
**Como** médico 
**quiero** gestionar datos de los pacientes
**para** actualizar dichos datos.

**Comment by 01Kwa** [comment]
Criterios de aceptación:

- Ingresar como médico para poder gestionar a pacientes.
- Seleccionar un paciente para gestionar sus datos.
- Elegir en agregar registro a su historial clínico o gestionar su perfil.

**Comment by 01Kwa** [comment]
.
