### ISSUE TITLE
US#6 | Buscar pacientes

### ISSUE THREAD

**Issue by FrancoSer** [FrancoSer/ISPC_2do_semestre_2022#18]
US#5
**Como** médico 
**quiero** poder buscar un paciente
**para** ver sus datos clínicos.

**Comment by 01Kwa** [comment]
Criterios de aceptación:

- Debe tener un icono que indique el historial.
- Página aparte de las demás secciones.
- Debe poseer un buscador que se ingresen números.
- El paciente debe tener registros en su historial clínico para poder verlo.

**Comment by 01Kwa** [comment]
.
