### ISSUE TITLE
US# | Ver perfil como paciente

### ISSUE THREAD

**Issue by FrancoSer** [FrancoSer/ISPC_2do_semestre_2022#20]
US#4
**Como** paciente 
**quiero** ir a mi perfil
**para** ver mis datos.

**Comment by 01Kwa** [comment]
Criterios de aceptación:

- Ingresar como paciente con CUIL y contraseña.
- Comprobar sus datos.
- Tener registros en su historial clínico.

**Comment by 01Kwa** [comment]
.
