### ISSUE TITLE
US#5 | Ingresar como UP.

### ISSUE THREAD

**Issue by FrancoSer** [FrancoSer/ISPC_2do_semestre_2022#22]
US#5
**Como** paciente 
**Quiero**  iniciar sesión
**Para** ingresar a la página como paciente.

[TK#2 | Pag. de Registro](https://github.com/FrancoSer/ISPC_2do_semestre_2022/issues/25)
[TK#3 | Inicio de sesión](https://github.com/FrancoSer/ISPC_2do_semestre_2022/issues/29)

**Comment by 01Kwa** [comment]
Criterios de aceptación

- Debe poseer CUIL y contraseña para registrarse como paciente.
- Debe tener datos registrados.

**Comment by 01Kwa** [comment]
.
