### ISSUE TITLE
US#4 | Ingresar como UM.

### ISSUE THREAD

**Issue by FrancoSer** [FrancoSer/ISPC_2do_semestre_2022#23]
US#4
**Como** médico 
**Quiero** iniciar sesión
**Para** ingresar a la página como médico.

[TK#1 ||| Index.](https://github.com/FrancoSer/ISPC_2do_semestre_2022/issues/28)
[TK#3 ||| Inicio de sesión](https://github.com/FrancoSer/ISPC_2do_semestre_2022/issues/29)

**Comment by 01Kwa** [comment]
Criterios de aceptación

- Debe poseer CUIL, matricula y contraseña para registrarse como médico.
- Los datos ingresados deben estar cargados para verificar que sea un profesional de la salud.

**Comment by Noegraf** [comment]
.
